### ISSUE TITLE
multiple ssid enable button color bug

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#6] opened 2014-08-28 09:58 UTC
On my RT AC66U i use 4 SSID's. standard is 2.4 and 5 Ghz enable. This works fine and button is gray if enable. If you use more then 2. The extra ssid's the enable button is the same as disable.

See screenshot what i mean.
http://i.imgur.com/AxjLc6y.png

**Comment by Jackysi** [comment] 2014-09-05 11:03
I'm working on this issue as I write, this is very strange issue indeed. Gives me headache!
Update: Actually, the issue is these buttons should not even be there, they should be hidden for virtual interfaces!
Update: After few hours of trying to debug the code I found the issue, now fixed!

**Closed as completed** 2014-09-05 22:20 UTC

**Comment by ghost** [comment] 2014-09-14 16:21
Its broken :(. Don't see the buttons any more

http://i.imgur.com/hrNirNi.png

**Comment by Jackysi** [comment] 2014-09-15 02:03
The buttons are supposed to be hidden for Virtual Wireless devices. See Shibby firmware for proof. Its logical virtual wireless devices can't be enabled/disabled since they're part of main radio antena which you can enable/disable.

**Comment by ghost** [comment] 2014-09-15 09:18
I can test right now the shibby version. Do that this week. But the previos version where the buttons are viseble if i press disable on the virtual wireless only that wireless wil be disable. In the current version where only root wireless see if i press disable the virtuale wireless still enable
