### ISSUE TITLE
IP Traffic Real-Time and 24h views are blank with Asus RT-AC68U

### ISSUE THREAD

**Issue by saintger** [Jackysi/advancedtomato#172] opened 2016-05-30 08:20 UTC
Router: Asus RT-AC68U
Advancedtomato: tomato-RT-AC68U-AT-ARM-3.1-136-AIO-64K.trx

Screenshots:
![real-time](https://cloud.githubusercontent.com/assets/1916284/15643725/32b804cc-264f-11e6-99b5-eb027059e060.png)
![24h ip traffic history](https://cloud.githubusercontent.com/assets/1916284/15643722/32a6691a-264f-11e6-915f-59f105c89b94.png)
![view graphs](https://cloud.githubusercontent.com/assets/1916284/15643727/32c5d85e-264f-11e6-8fbe-67d16ba9151e.png)
![transfer rates](https://cloud.githubusercontent.com/assets/1916284/15643726/32bdfeae-264f-11e6-9515-febe7295af43.png)
![daily](https://cloud.githubusercontent.com/assets/1916284/15643723/32aa9896-264f-11e6-91ef-e17770ee8bff.png)
![monthly](https://cloud.githubusercontent.com/assets/1916284/15643724/32b17d14-264f-11e6-9622-7974d06d3c01.png)

I haven't managed to display the IP traffic with Advancedtomato (either real-time or last 24h). The X-axis and Y-axis are updated (i.e. scaled according to the current IP traffic) but I don't see any plot (see screenshots).

Bandwidth monitoring works fine (I can see the plot), and other views (View Graphs, Transfer Rates, Daily and Monthly) seem to work fine.

IP Traffic monitoring is enabled in the Administration Panel (I haven't changed the default configuration) and I have tried with both static and dynamic IP. With static IP, I have checked "Bound To" and "IPTraffic" for each static IP (I have also tried without theses checkboxes checked).

I have search this issue and it seems that nobody else had this issue before. Perhaps I have forgot to activate an option somewhere ?

**Comment by Jackysi** [comment] 2016-05-30 09:41
Mm I honestly don't know for sure what's the problem (I'm only GUI developer and not exactly expert on Networks and Tomato). However I can say that its not "AdvancedTomato" issue it self (This is GUI on top of Tomato By Shibby) so in this case I have to close the issue.

If it were me, I'd seek help at http://linksysinfo.org/ and try again by defaults (resetting nvram and reflashing image). Also maybe check if there are javascript errors in F12 Console.

**Closed as completed by Jackysi** 2016-05-30 09:41 UTC
Labels: firmware

**Comment by saintger** [comment] 2016-05-30 16:59
Just for info, I have installed Tomato by Shibby and the Real-Time IP Traffic monitoring works perfectly.
So I am not sure that the problem is in Tomato by Shibby.

**Comment by Jackysi** [comment] 2016-05-30 18:31
I have R7000 and RT-N66U and I can verify that Real Time IP Traffic works fine on both. With that in mind there is no custom image for AC68U and so I believe the issue is related to your router or NVRAM settings.
