### ISSUE TITLE
Links on QOS view graphs pages result in error notification

### ISSUE THREAD

**Issue by paulvizard** [Jackysi/advancedtomato#9] opened 2014-09-08 01:00 UTC
2.02.20 K26 USB AIO

When clicking on a segment of the pie chart or a link in the class list (below the pie charts), the following error is shown:

ERROR occured!
There has been error while loading a page, please review debug data
bellow if this is isolated issue.
Otherwise please leave a message at http://advancedtomato.com [1].
TypeError: 'null' is not an object (evaluating 'E('stitle').innerHTML
= 'Details: ' + abc[viewClass] + ' '')

**Comment by Jackysi** [comment] 2014-09-10 13:28
Thanks for report! Looking into it!

**Comment by Jackysi** [comment] 2014-10-25 16:28
Its been long time since this issue was opened, I have no updates just yet :( I couldn't re-produce the issue. I'm releasing new update 2.4-123 soon which may fix this issue, if not I optimized error page to show more details which could bring me closer to finding a solution. Thanks!

**Comment by manuelski** [comment] 2014-11-02 19:22
Error still persists
TypeError: Cannot set property 'innerHTML' of null
    at init (eval at  (http://192.168.1.1/js/jquery.min.js:2:4243), :335:44)
    at eval (eval at  (http://192.168.1.1/js/jquery.min.js:2:4243), :1:1)
    at eval (native)
    at Function.x.extend.globalEval (http://192.168.1.1/js/jquery.min.js:2:4243)
    at x.fn.extend.domManip (http://192.168.1.1/js/jquery.min.js:3:21416)
    at x.fn.extend.append (http://192.168.1.1/js/jquery.min.js:3:18985)
    at null. (http://192.168.1.1/js/jquery.min.js:3:20357)
    at Function.x.extend.access (http://192.168.1.1/js/jquery.min.js:2:5780)
    at x.fn.extend.html (http://192.168.1.1/js/jquery.min.js:3:20020)
    at Object.TomatoAJAX.onCompleted (http://192.168.1.1/js/advancedtomato.js:215:36)Cannot set property 'innerHTML' of null

Netgear WNR3500L v2

if you need more info then let me know

**Comment by francoisjacques** [comment] 2014-11-21 13:51
Confirmed. Chrome Version 33.0.1750.146 for MacOSX
Linksys E2500 router.

**Comment by Jackysi** [comment] 2014-12-21 12:36
This issue has finally been fixed and its ready to be released with new update. See details:
https://github.com/Jackysi/advancedtomato2/issues/21

**Closed as completed by Jackysi** 2014-12-21 12:36 UTC
